export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
export const SET_SELECTED_IMAGE = 'SET_SELECTED_IMAGE';
export const CLEAR_SELECTED_IMAGE = 'CLEAR_SELECTED_IMAGE';